-- Trainer activity approval workflow: change requests, approval_status, RPC.

create table if not exists public.activity_change_requests (
  id bigint generated by default as identity primary key,
  trainer_id bigint not null references public.trainers(id) on delete restrict,
  trainer_project_id bigint references public.trainer_projects(id) on delete set null,
  change_type text not null check (change_type in ('create', 'update', 'delete')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  proposed_payload jsonb,
  previous_payload jsonb,
  submitted_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null,
  review_notes text,
  result_trainer_project_id bigint references public.trainer_projects(id) on delete set null
);

create index if not exists activity_change_requests_pending_idx
  on public.activity_change_requests (status)
  where status = 'pending';

create index if not exists activity_change_requests_trainer_submitted_idx
  on public.activity_change_requests (trainer_id, submitted_at desc);

alter table public.trainer_projects
  add column if not exists approval_status text not null default 'approved'
  check (approval_status in ('approved', 'pending', 'rejected'));

update public.trainer_projects
set approval_status = 'approved'
where approval_status is distinct from 'approved';

-- RLS: activity_change_requests
alter table public.activity_change_requests enable row level security;

create policy activity_change_requests_admin_all on public.activity_change_requests
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy activity_change_requests_trainer_select on public.activity_change_requests
  for select to authenticated
  using (trainer_id = public.auth_trainer_id());

-- RLS: trainer_projects — trainers see approved rows + own pending/rejected
drop policy if exists trainer_projects_trainer_select on public.trainer_projects;
drop policy if exists trainer_projects_trainer_insert on public.trainer_projects;
drop policy if exists trainer_projects_trainer_update on public.trainer_projects;
drop policy if exists trainer_projects_trainer_delete on public.trainer_projects;

create policy trainer_projects_trainer_select on public.trainer_projects
  for select to authenticated
  using (
    public.auth_trainer_id() is not null
    and (
      approval_status = 'approved'
      or (
        trainer_id = public.auth_trainer_id()
        and approval_status in ('pending', 'rejected')
      )
    )
  );

-- Trainers write only through SECURITY DEFINER RPC (no direct insert/update/delete policies).

create or replace function public.row_to_activity_payload(p_row public.trainer_projects)
returns jsonb
language sql
immutable
as $$
  select jsonb_build_object(
    'project_type_id', p_row.project_type_id,
    'project_main_id', p_row.project_main_id,
    'project_sub', p_row.project_sub,
    'role_id', p_row.role_id,
    'activity_type_id', p_row.activity_type_id,
    'delivery_format_id', p_row.delivery_format_id,
    'recurrence_type_id', p_row.recurrence_type_id,
    'start_datetime', p_row.start_datetime,
    'end_datetime', p_row.end_datetime,
    'start_date', p_row.start_date,
    'end_date', p_row.end_date,
    'task_desc', p_row.task_desc,
    'comments', p_row.comments,
    'is_duplicate', coalesce(p_row.is_duplicate, false)
  );
$$;

create or replace function public.apply_activity_payload(
  p_row public.trainer_projects,
  p_payload jsonb
)
returns public.trainer_projects
language sql
immutable
as $$
  select jsonb_populate_record(p_row, p_payload);
$$;

create or replace function public.submit_trainer_activity_change(
  p_change_type text,
  p_trainer_project_id bigint,
  p_payload jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_trainer_id bigint;
  v_current public.trainer_projects%rowtype;
  v_payload public.trainer_projects%rowtype;
  v_request_id bigint;
  v_new_id bigint;
begin
  if public.is_admin() then
    raise exception 'Administrators must use save_trainer_activity directly';
  end if;

  v_trainer_id := public.auth_trainer_id();
  if v_trainer_id is null then
    raise exception 'Unauthorized';
  end if;

  if p_change_type not in ('create', 'update', 'delete') then
    raise exception 'Invalid change type: %', p_change_type;
  end if;

  if p_change_type = 'create' then
    if p_trainer_project_id is not null then
      raise exception 'trainer_project_id must be null for create';
    end if;
    if p_payload is null then
      raise exception 'Payload is required for create';
    end if;

    v_payload := jsonb_populate_record(null::public.trainer_projects, p_payload);

    insert into public.trainer_projects (
      trainer_id, approval_status,
      project_type_id, project_main_id, project_sub,
      role_id, activity_type_id, delivery_format_id, recurrence_type_id,
      start_datetime, end_datetime, start_date, end_date,
      task_desc, comments, is_duplicate
    )
    values (
      v_trainer_id, 'pending',
      v_payload.project_type_id, v_payload.project_main_id, v_payload.project_sub,
      v_payload.role_id, v_payload.activity_type_id, v_payload.delivery_format_id,
      v_payload.recurrence_type_id,
      v_payload.start_datetime, v_payload.end_datetime, v_payload.start_date,
      v_payload.end_date, v_payload.task_desc, v_payload.comments,
      coalesce(v_payload.is_duplicate, false)
    )
    returning id into v_new_id;

    insert into public.activity_change_requests (
      trainer_id, trainer_project_id, change_type, status,
      proposed_payload, previous_payload, result_trainer_project_id
    )
    values (
      v_trainer_id, v_new_id, 'create', 'pending',
      p_payload, null, v_new_id
    )
    returning id into v_request_id;

    return v_request_id;
  end if;

  if p_trainer_project_id is null then
    raise exception 'trainer_project_id is required for %', p_change_type;
  end if;

  select *
  into v_current
  from public.trainer_projects
  where id = p_trainer_project_id;

  if not found then
    raise exception 'Activity % was not found', p_trainer_project_id;
  end if;

  if v_current.trainer_id <> v_trainer_id then
    raise exception 'Cannot modify another trainer''s activity';
  end if;

  if v_current.approval_status = 'pending' and p_change_type <> 'delete' then
    raise exception 'Activity is already pending approval';
  end if;

  -- Replace an existing pending request for the same row.
  update public.activity_change_requests
  set status = 'rejected',
      reviewed_at = now(),
      review_notes = 'Superseded by a newer submission'
  where trainer_project_id = p_trainer_project_id
    and status = 'pending';

  if p_change_type = 'update' then
    if p_payload is null then
      raise exception 'Payload is required for update';
    end if;
    if v_current.approval_status <> 'approved' then
      raise exception 'Only approved activities can be updated through approval';
    end if;

    insert into public.activity_change_requests (
      trainer_id, trainer_project_id, change_type, status,
      proposed_payload, previous_payload
    )
    values (
      v_trainer_id, p_trainer_project_id, 'update', 'pending',
      p_payload, public.row_to_activity_payload(v_current)
    )
    returning id into v_request_id;

    return v_request_id;
  end if;

  -- delete
  if v_current.approval_status = 'pending' then
    delete from public.trainer_projects where id = p_trainer_project_id;
    return null;
  end if;

  insert into public.activity_change_requests (
    trainer_id, trainer_project_id, change_type, status,
    proposed_payload, previous_payload
  )
  values (
    v_trainer_id, p_trainer_project_id, 'delete', 'pending',
    null, public.row_to_activity_payload(v_current)
  )
  returning id into v_request_id;

  return v_request_id;
end;
$$;

create or replace function public.approve_activity_change(p_request_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.activity_change_requests%rowtype;
  v_payload public.trainer_projects%rowtype;
  v_row public.trainer_projects%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Only administrators can approve changes';
  end if;

  select *
  into v_request
  from public.activity_change_requests
  where id = p_request_id
  for update;

  if not found then
    raise exception 'Request % was not found', p_request_id;
  end if;

  if v_request.status <> 'pending' then
    raise exception 'Request % is not pending', p_request_id;
  end if;

  if v_request.change_type = 'create' then
    update public.trainer_projects
    set approval_status = 'approved'
    where id = v_request.trainer_project_id;

    update public.activity_change_requests
    set
      status = 'approved',
      reviewed_at = now(),
      reviewed_by = auth.uid(),
      result_trainer_project_id = v_request.trainer_project_id
    where id = p_request_id;
    return;
  end if;

  if v_request.change_type = 'update' then
    select *
    into v_row
    from public.trainer_projects
    where id = v_request.trainer_project_id
    for update;

    if not found then
      raise exception 'Activity % was not found', v_request.trainer_project_id;
    end if;

    v_payload := jsonb_populate_record(v_row, v_request.proposed_payload);

    update public.trainer_projects
    set
      project_type_id = v_payload.project_type_id,
      project_main_id = v_payload.project_main_id,
      project_sub = v_payload.project_sub,
      role_id = v_payload.role_id,
      activity_type_id = v_payload.activity_type_id,
      delivery_format_id = v_payload.delivery_format_id,
      recurrence_type_id = v_payload.recurrence_type_id,
      start_datetime = v_payload.start_datetime,
      end_datetime = v_payload.end_datetime,
      start_date = v_payload.start_date,
      end_date = v_payload.end_date,
      task_desc = v_payload.task_desc,
      comments = v_payload.comments,
      is_duplicate = coalesce(v_payload.is_duplicate, false),
      approval_status = 'approved'
    where id = v_request.trainer_project_id;

    update public.activity_change_requests
    set
      status = 'approved',
      reviewed_at = now(),
      reviewed_by = auth.uid(),
      result_trainer_project_id = v_request.trainer_project_id
    where id = p_request_id;
    return;
  end if;

  -- delete
  delete from public.trainer_projects
  where id = v_request.trainer_project_id;

  update public.activity_change_requests
  set
    status = 'approved',
    reviewed_at = now(),
    reviewed_by = auth.uid(),
    result_trainer_project_id = v_request.trainer_project_id
  where id = p_request_id;
end;
$$;

create or replace function public.reject_activity_change(
  p_request_id bigint,
  p_notes text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.activity_change_requests%rowtype;
begin
  if not public.is_admin() then
    raise exception 'Only administrators can reject changes';
  end if;

  select *
  into v_request
  from public.activity_change_requests
  where id = p_request_id
  for update;

  if not found then
    raise exception 'Request % was not found', p_request_id;
  end if;

  if v_request.status <> 'pending' then
    raise exception 'Request % is not pending', p_request_id;
  end if;

  if v_request.change_type = 'create' then
    update public.trainer_projects
    set approval_status = 'rejected'
    where id = v_request.trainer_project_id;
  end if;

  update public.activity_change_requests
  set
    status = 'rejected',
    reviewed_at = now(),
    reviewed_by = auth.uid(),
    review_notes = p_notes
  where id = p_request_id;
end;
$$;

create or replace function public.count_pending_activity_change_requests()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select case
    when public.is_admin() then (
      select count(*)::bigint
      from public.activity_change_requests
      where status = 'pending'
    )
    else 0::bigint
  end;
$$;

-- Block trainers from direct save_trainer_activity (must use submit flow).
create or replace function public.save_trainer_activity(
  p_record_id bigint,
  p_trainer_id bigint,
  p_participant_ids bigint[],
  p_can_manage_participants boolean,
  p_payload jsonb
) returns void
language plpgsql
set search_path = public
as $$
declare
  v_current public.trainer_projects%rowtype;
  v_payload public.trainer_projects%rowtype;
  v_group_id uuid;
  v_primary_trainer_id bigint;
begin
  if not public.is_admin() then
    raise exception 'Trainers must use submit_trainer_activity_change';
  end if;

  if coalesce(cardinality(p_participant_ids), 0) = 0 then
    raise exception 'At least one participant is required';
  end if;

  v_payload := jsonb_populate_record(null::public.trainer_projects, p_payload);
  v_primary_trainer_id := p_participant_ids[1];

  if p_record_id is null then
    v_group_id := case
      when cardinality(p_participant_ids) > 1 then gen_random_uuid()
      else null
    end;

    insert into public.trainer_projects (
      trainer_id, event_group_id, approval_status,
      project_type_id, project_main_id, project_sub,
      role_id, activity_type_id, delivery_format_id, recurrence_type_id,
      start_datetime, end_datetime, start_date, end_date,
      task_desc, comments, is_duplicate
    )
    select
      participant_id, v_group_id, 'approved',
      v_payload.project_type_id, v_payload.project_main_id,
      v_payload.project_sub, v_payload.role_id, v_payload.activity_type_id,
      v_payload.delivery_format_id, v_payload.recurrence_type_id,
      v_payload.start_datetime, v_payload.end_datetime, v_payload.start_date,
      v_payload.end_date, v_payload.task_desc, v_payload.comments,
      coalesce(v_payload.is_duplicate, false)
    from unnest(p_participant_ids) as participant_id;
    return;
  end if;

  select *
  into v_current
  from public.trainer_projects
  where id = p_record_id
  for update;

  if not found then
    raise exception 'Activity % was not found', p_record_id;
  end if;

  if v_current.event_group_id is not null then
    if not p_can_manage_participants then
      raise exception 'Only an administrator can edit a group activity row';
    end if;
    v_group_id := v_current.event_group_id;

    update public.trainer_projects
    set
      project_type_id = v_payload.project_type_id,
      project_main_id = v_payload.project_main_id,
      project_sub = v_payload.project_sub,
      role_id = v_payload.role_id,
      activity_type_id = v_payload.activity_type_id,
      delivery_format_id = v_payload.delivery_format_id,
      recurrence_type_id = v_payload.recurrence_type_id,
      start_datetime = v_payload.start_datetime,
      end_datetime = v_payload.end_datetime,
      start_date = v_payload.start_date,
      end_date = v_payload.end_date,
      task_desc = v_payload.task_desc,
      comments = v_payload.comments,
      is_duplicate = coalesce(v_payload.is_duplicate, false)
    where event_group_id = v_group_id;

    delete from public.trainer_projects
    where event_group_id = v_group_id
      and not (trainer_id = any(p_participant_ids));

    insert into public.trainer_projects (
      trainer_id, event_group_id, approval_status,
      project_type_id, project_main_id, project_sub,
      role_id, activity_type_id, delivery_format_id, recurrence_type_id,
      start_datetime, end_datetime, start_date, end_date,
      task_desc, comments, is_duplicate
    )
    select
      participant_id, v_group_id, 'approved',
      v_payload.project_type_id, v_payload.project_main_id,
      v_payload.project_sub, v_payload.role_id, v_payload.activity_type_id,
      v_payload.delivery_format_id, v_payload.recurrence_type_id,
      v_payload.start_datetime, v_payload.end_datetime, v_payload.start_date,
      v_payload.end_date, v_payload.task_desc, v_payload.comments,
      coalesce(v_payload.is_duplicate, false)
    from unnest(p_participant_ids) as participant_id
    where not exists (
      select 1
      from public.trainer_projects existing
      where existing.event_group_id = v_group_id
        and existing.trainer_id = participant_id
    );
    return;
  end if;

  v_group_id := case
    when cardinality(p_participant_ids) > 1 then gen_random_uuid()
    else null
  end;

  update public.trainer_projects
  set
    trainer_id = v_primary_trainer_id,
    event_group_id = v_group_id,
    project_type_id = v_payload.project_type_id,
    project_main_id = v_payload.project_main_id,
    project_sub = v_payload.project_sub,
    role_id = v_payload.role_id,
    activity_type_id = v_payload.activity_type_id,
    delivery_format_id = v_payload.delivery_format_id,
    recurrence_type_id = v_payload.recurrence_type_id,
    start_datetime = v_payload.start_datetime,
    end_datetime = v_payload.end_datetime,
    start_date = v_payload.start_date,
    end_date = v_payload.end_date,
    task_desc = v_payload.task_desc,
    comments = v_payload.comments,
    is_duplicate = coalesce(v_payload.is_duplicate, false)
  where id = p_record_id;

  if v_group_id is not null then
    insert into public.trainer_projects (
      trainer_id, event_group_id, approval_status,
      project_type_id, project_main_id, project_sub,
      role_id, activity_type_id, delivery_format_id, recurrence_type_id,
      start_datetime, end_datetime, start_date, end_date,
      task_desc, comments, is_duplicate
    )
    select
      participant_id, v_group_id, 'approved',
      v_payload.project_type_id, v_payload.project_main_id,
      v_payload.project_sub, v_payload.role_id, v_payload.activity_type_id,
      v_payload.delivery_format_id, v_payload.recurrence_type_id,
      v_payload.start_datetime, v_payload.end_datetime, v_payload.start_date,
      v_payload.end_date, v_payload.task_desc, v_payload.comments,
      coalesce(v_payload.is_duplicate, false)
    from unnest(p_participant_ids[2:cardinality(p_participant_ids)]) as participant_id;
  end if;
end;
$$;

grant execute on function public.submit_trainer_activity_change(text, bigint, jsonb) to authenticated;
grant execute on function public.approve_activity_change(bigint) to authenticated;
grant execute on function public.reject_activity_change(bigint, text) to authenticated;
grant execute on function public.count_pending_activity_change_requests() to authenticated;

notify pgrst, 'reload schema';
