alter table public.project_names
  add column if not exists is_in_application_campaign boolean not null default false;

comment on column public.project_names.is_in_application_campaign is
  'Whether the project or program is included in the application campaign.';

create table if not exists public.production_calendar_days (
  id bigint generated by default as identity primary key,
  event_date date not null unique,
  day_type text not null,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint production_calendar_days_name_not_blank
    check (btrim(name) <> ''),
  constraint production_calendar_days_type_check
    check (day_type in ('holiday', 'working_saturday'))
);

insert into public.production_calendar_days (event_date, day_type, name)
values
  ('2027-01-01', 'holiday', 'Новогодние каникулы'),
  ('2027-01-02', 'holiday', 'Новогодние каникулы'),
  ('2027-01-03', 'holiday', 'Новогодние каникулы'),
  ('2027-01-04', 'holiday', 'Новогодние каникулы'),
  ('2027-01-05', 'holiday', 'Новогодние каникулы'),
  ('2027-01-06', 'holiday', 'Новогодние каникулы'),
  ('2027-01-07', 'holiday', 'Рождество Христово'),
  ('2027-01-08', 'holiday', 'Новогодние каникулы'),
  ('2027-02-22', 'holiday', 'Перенос выходного дня'),
  ('2027-02-23', 'holiday', 'День защитника Отечества'),
  ('2027-03-08', 'holiday', 'Международный женский день'),
  ('2027-05-01', 'holiday', 'Праздник Весны и Труда'),
  ('2027-05-03', 'holiday', 'Перенос выходного дня'),
  ('2027-05-09', 'holiday', 'День Победы'),
  ('2027-05-10', 'holiday', 'Перенос выходного дня'),
  ('2027-06-12', 'holiday', 'День России'),
  ('2027-06-14', 'holiday', 'Перенос выходного дня'),
  ('2027-11-04', 'holiday', 'День народного единства'),
  ('2027-11-05', 'holiday', 'Перенос выходного дня'),
  ('2027-12-31', 'holiday', 'Дополнительный выходной'),
  ('2027-02-20', 'working_saturday', 'Рабочий день в счёт переноса'),
  ('2027-04-30', 'working_saturday', 'Рабочий день в счёт переноса'),
  ('2027-06-11', 'working_saturday', 'Рабочий день в счёт переноса')
on conflict (event_date) do update
set day_type = excluded.day_type,
    name = excluded.name,
    updated_at = now();

create or replace function public.save_project_card(
  p_project_id bigint,
  p_payload jsonb,
  p_direction_ids bigint[] default '{}'::bigint[]
)
returns bigint
language plpgsql
set search_path = public
as $$
declare
  v_project_id bigint;
begin
  if p_project_id is null then
    insert into public.project_names (
      name, audit_index, weight, status_code, project_type_id, parent_project_id,
      module_position, customer, lead_methodologist_id, target_audience, goals,
      short_description, duration_days, duration_hours, participant_count,
      central_office_format_code, main_department_format_code, annual_budget_item_id,
      is_in_application_campaign
    )
    values (
      nullif(btrim(p_payload->>'name'), ''),
      nullif(btrim(p_payload->>'audit_index'), ''),
      coalesce((p_payload->>'weight')::numeric, 1),
      coalesce(nullif(p_payload->>'status_code', ''), 'under_review'),
      (p_payload->>'project_type_id')::bigint,
      (p_payload->>'parent_project_id')::bigint,
      (p_payload->>'module_position')::integer,
      nullif(btrim(p_payload->>'customer'), ''),
      (p_payload->>'lead_methodologist_id')::bigint,
      nullif(btrim(p_payload->>'target_audience'), ''),
      nullif(btrim(p_payload->>'goals'), ''),
      nullif(btrim(p_payload->>'short_description'), ''),
      (p_payload->>'duration_days')::numeric,
      (p_payload->>'duration_hours')::numeric,
      (p_payload->>'participant_count')::integer,
      nullif(p_payload->>'central_office_format_code', ''),
      nullif(p_payload->>'main_department_format_code', ''),
      (p_payload->>'annual_budget_item_id')::bigint,
      coalesce((p_payload->>'is_in_application_campaign')::boolean, false)
    )
    returning id into v_project_id;
  else
    update public.project_names
    set name = nullif(btrim(p_payload->>'name'), ''),
        audit_index = nullif(btrim(p_payload->>'audit_index'), ''),
        weight = coalesce((p_payload->>'weight')::numeric, 1),
        status_code = coalesce(nullif(p_payload->>'status_code', ''), 'under_review'),
        project_type_id = (p_payload->>'project_type_id')::bigint,
        parent_project_id = (p_payload->>'parent_project_id')::bigint,
        module_position = (p_payload->>'module_position')::integer,
        customer = nullif(btrim(p_payload->>'customer'), ''),
        lead_methodologist_id = (p_payload->>'lead_methodologist_id')::bigint,
        target_audience = nullif(btrim(p_payload->>'target_audience'), ''),
        goals = nullif(btrim(p_payload->>'goals'), ''),
        short_description = nullif(btrim(p_payload->>'short_description'), ''),
        duration_days = (p_payload->>'duration_days')::numeric,
        duration_hours = (p_payload->>'duration_hours')::numeric,
        participant_count = (p_payload->>'participant_count')::integer,
        central_office_format_code = nullif(p_payload->>'central_office_format_code', ''),
        main_department_format_code = nullif(p_payload->>'main_department_format_code', ''),
        annual_budget_item_id = (p_payload->>'annual_budget_item_id')::bigint,
        is_in_application_campaign = coalesce(
          (p_payload->>'is_in_application_campaign')::boolean,
          false
        )
    where id = p_project_id
    returning id into v_project_id;

    if v_project_id is null then
      raise exception 'Project % not found', p_project_id using errcode = 'P0002';
    end if;
  end if;

  delete from public.project_direction_links
  where project_id = v_project_id;

  insert into public.project_direction_links (project_id, direction_id)
  select v_project_id, direction_id
  from unnest(coalesce(p_direction_ids, '{}'::bigint[])) as direction_id;

  return v_project_id;
end;
$$;

grant select, insert, update, delete on table public.production_calendar_days
  to anon, authenticated;
grant usage, select on sequence public.production_calendar_days_id_seq
  to anon, authenticated;

notify pgrst, 'reload schema';
