alter table public.project_names
  add column if not exists module_gap_value integer,
  add column if not exists module_gap_unit text;

alter table public.project_names
  drop constraint if exists project_names_module_gap_value_check;
alter table public.project_names
  add constraint project_names_module_gap_value_check
  check (module_gap_value is null or module_gap_value >= 0);

alter table public.project_names
  drop constraint if exists project_names_module_gap_unit_check;
alter table public.project_names
  add constraint project_names_module_gap_unit_check
  check (module_gap_unit is null or module_gap_unit in ('days', 'weeks', 'months', 'quarters'));

create table if not exists public.program_schedules (
  id bigint generated by default as identity primary key,
  program_project_id integer not null references public.project_names(id) on delete cascade,
  start_date date not null,
  gap_value integer not null,
  gap_unit text not null,
  calendar_mode text not null default 'working',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint program_schedules_gap_value_check check (gap_value >= 0),
  constraint program_schedules_gap_unit_check check (gap_unit in ('days', 'weeks', 'months', 'quarters')),
  constraint program_schedules_calendar_mode_check check (calendar_mode in ('working', 'calendar'))
);

create table if not exists public.program_schedule_modules (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null references public.program_schedules(id) on delete cascade,
  module_project_id integer not null references public.project_names(id) on delete restrict,
  module_position integer,
  duration_days numeric not null,
  planned_start_date date not null,
  planned_end_date date not null,
  admin_calendar_event_id bigint,
  created_at timestamptz not null default now(),
  constraint program_schedule_modules_duration_check check (duration_days > 0),
  constraint program_schedule_modules_dates_check check (planned_end_date >= planned_start_date),
  constraint program_schedule_modules_unique_module unique (schedule_id, module_project_id)
);

alter table public.admin_calendar_events
  add column if not exists program_schedule_id bigint,
  add column if not exists program_schedule_module_id bigint;

create index if not exists program_schedules_program_idx
  on public.program_schedules(program_project_id, start_date);
create index if not exists program_schedule_modules_schedule_idx
  on public.program_schedule_modules(schedule_id, planned_start_date);
create index if not exists admin_calendar_events_program_schedule_idx
  on public.admin_calendar_events(program_schedule_id, program_schedule_module_id);

grant select, insert, update, delete on table public.program_schedules to anon, authenticated;
grant select, insert, update, delete on table public.program_schedule_modules to anon, authenticated;
grant usage, select on sequence public.program_schedules_id_seq to anon, authenticated;
grant usage, select on sequence public.program_schedule_modules_id_seq to anon, authenticated;
grant select, insert, update on table public.admin_calendar_events to anon, authenticated;

create or replace function public.save_program_schedule(
  p_program_project_id bigint,
  p_start_date date,
  p_gap_value integer,
  p_gap_unit text,
  p_calendar_mode text,
  p_modules jsonb
)
returns bigint
language plpgsql
set search_path = public
as $$
declare
  v_schedule_id bigint;
  v_module jsonb;
  v_module_id bigint;
  v_event_id bigint;
  v_program_name text;
begin
  if p_modules is null or jsonb_array_length(p_modules) = 0 then
    raise exception 'A modular program must contain at least one module' using errcode = '22023';
  end if;

  select name into v_program_name from public.project_names where id = p_program_project_id;
  if v_program_name is null then
    raise exception 'Program % not found', p_program_project_id using errcode = 'P0002';
  end if;

  insert into public.program_schedules (
    program_project_id, start_date, gap_value, gap_unit, calendar_mode
  ) values (
    p_program_project_id, p_start_date, p_gap_value, p_gap_unit, coalesce(nullif(p_calendar_mode, ''), 'working')
  ) returning id into v_schedule_id;

  for v_module in select value from jsonb_array_elements(p_modules) loop
    insert into public.program_schedule_modules (
      schedule_id, module_project_id, module_position, duration_days,
      planned_start_date, planned_end_date
    ) values (
      v_schedule_id,
      (v_module->>'module_project_id')::bigint,
      (v_module->>'module_position')::integer,
      (v_module->>'duration_days')::numeric,
      (v_module->>'planned_start_date')::date,
      (v_module->>'planned_end_date')::date
    ) returning id into v_module_id;

    insert into public.admin_calendar_events (
      project_main_id,
      title,
      required_trainer_count,
      start_date,
      end_date,
      description,
      comments,
      occurrence_index,
      program_schedule_id,
      program_schedule_module_id
    ) values (
      (v_module->>'module_project_id')::bigint,
      coalesce((select name from public.project_names where id = (v_module->>'module_project_id')::bigint), 'Модуль'),
      1,
      (v_module->>'planned_start_date')::date,
      (v_module->>'planned_end_date')::date,
      'Модуль программы «' || v_program_name || '»',
      'Создано планированием программы',
      coalesce((v_module->>'module_position')::integer - 1, 0),
      v_schedule_id,
      v_module_id
    ) returning id into v_event_id;

    update public.program_schedule_modules
      set admin_calendar_event_id = v_event_id
      where id = v_module_id;
  end loop;

  return v_schedule_id;
end;
$$;

revoke all on function public.save_program_schedule(bigint, date, integer, text, text, jsonb) from public;
grant execute on function public.save_program_schedule(bigint, date, integer, text, text, jsonb) to anon, authenticated;

notify pgrst, 'reload schema';
