create table if not exists public.admin_calendar_events (
  id bigint generated by default as identity primary key,
  series_id uuid not null default gen_random_uuid(),
  copied_from_event_id bigint references public.admin_calendar_events(id) on delete set null,
  project_main_id bigint references public.project_names(id) on delete set null,
  activity_type_id bigint references public.activity_types(id) on delete set null,
  delivery_format_id bigint references public.delivery_formats(id) on delete set null,
  recurrence_type_id bigint references public.recurrence_types(id) on delete set null,
  title text not null,
  required_trainer_count integer not null default 1,
  start_datetime timestamptz,
  end_datetime timestamptz,
  start_date date,
  end_date date,
  recurrence_until date,
  occurrence_index integer not null default 0,
  description text,
  comments text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint admin_calendar_events_title_not_blank check (btrim(title) <> ''),
  constraint admin_calendar_events_required_trainers_positive check (required_trainer_count > 0),
  constraint admin_calendar_events_occurrence_index_nonnegative check (occurrence_index >= 0),
  constraint admin_calendar_events_schedule_check check (
    (start_datetime is not null and end_datetime is not null
      and start_date is null and end_date is null and end_datetime > start_datetime)
    or
    (start_datetime is null and end_datetime is null
      and start_date is not null and end_date is not null and end_date >= start_date)
  )
);

create index if not exists admin_calendar_events_series_idx
  on public.admin_calendar_events(series_id, occurrence_index);
create index if not exists admin_calendar_events_start_datetime_idx
  on public.admin_calendar_events(start_datetime);
create index if not exists admin_calendar_events_start_date_idx
  on public.admin_calendar_events(start_date);

comment on table public.admin_calendar_events is
  'Administrator-planned calendar events before individual trainers are assigned.';
comment on column public.admin_calendar_events.required_trainer_count is
  'Planned number of trainers required for the event.';

grant select, insert, update, delete on table public.admin_calendar_events to anon, authenticated;
grant usage, select on sequence public.admin_calendar_events_id_seq to anon, authenticated;
