create table if not exists public.trainers (
  id bigint generated by default as identity primary key,
  full_name text not null
);

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  name text not null,
  weight numeric default 1
);

create table if not exists public.project_types (
  id bigint generated by default as identity primary key,
  name text not null,
  weight numeric default 1
);

create table if not exists public.project_names (
  id bigint generated by default as identity primary key,
  name text not null,
  weight numeric default 1
);

create table if not exists public.activity_types (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  weight numeric default 1,
  is_active boolean not null default true
);

create table if not exists public.delivery_formats (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  weight numeric default 1,
  is_active boolean not null default true
);

create table if not exists public.recurrence_types (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  weight numeric default 1,
  is_active boolean not null default true
);

create table if not exists public.trainer_projects (
  id bigint generated by default as identity primary key,
  trainer_id bigint not null references public.trainers(id) on delete restrict,
  project_type_id bigint references public.project_types(id) on delete restrict,
  project_main_id bigint references public.project_names(id) on delete restrict,
  project_sub text,
  role_id bigint references public.roles(id) on delete restrict,
  activity_type_id bigint references public.activity_types(id) on delete restrict,
  delivery_format_id bigint references public.delivery_formats(id) on delete restrict,
  recurrence_type_id bigint references public.recurrence_types(id) on delete restrict,
  start_datetime timestamptz,
  end_datetime timestamptz,
  start_date date,
  end_date date,
  source_type text,
  source_file text,
  source_schedule_key text,
  source_sheet text,
  source_range text,
  source_event_key text,
  is_duplicate boolean not null default false,
  task_desc text,
  comments text,
  constraint trainer_projects_schedule_check check (
    (
      start_datetime is not null
      and end_datetime is not null
      and start_date is null
      and end_date is null
      and end_datetime > start_datetime
    )
    or (
      start_datetime is null
      and end_datetime is null
      and start_date is not null
      and end_date is not null
      and end_date >= start_date
    )
    or (
      start_datetime is null
      and end_datetime is null
      and start_date is null
      and end_date is null
    )
  )
);

create index if not exists trainer_projects_trainer_id_idx
  on public.trainer_projects (trainer_id);
create index if not exists trainer_projects_project_main_id_idx
  on public.trainer_projects (project_main_id);
create index if not exists trainer_projects_start_datetime_idx
  on public.trainer_projects (start_datetime);
create index if not exists trainer_projects_start_date_idx
  on public.trainer_projects (start_date);

comment on table public.project_names is
  'Projects. The legacy table name is kept for backward compatibility.';
comment on table public.trainer_projects is
  'Trainer activities/assignments. The legacy table name is kept for backward compatibility.';
