create table if not exists public.project_delivery_formats (
  code text primary key,
  name text not null unique,
  sort_order integer not null default 0,
  is_active boolean not null default true
);

insert into public.project_delivery_formats (code, name, sort_order, is_active)
values
  ('in_person', 'Очно', 10, true),
  ('online', 'Онлайн', 20, true),
  ('hybrid', 'Очно/онлайн', 30, true)
on conflict (code) do update
set name = excluded.name,
    sort_order = excluded.sort_order,
    is_active = excluded.is_active;

create table if not exists public.annual_budget_items (
  id bigint generated by default as identity primary key,
  name text not null,
  is_active boolean not null default true,
  constraint annual_budget_items_name_not_blank check (btrim(name) <> '')
);

create unique index if not exists annual_budget_items_name_unique_idx
  on public.annual_budget_items (lower(btrim(name)));

insert into public.annual_budget_items (name)
select 'Программы подготовки руководителей'
where not exists (
  select 1
  from public.annual_budget_items
  where lower(btrim(name)) = lower('Программы подготовки руководителей')
);

alter table public.project_names
  add column if not exists central_office_format_code text,
  add column if not exists main_department_format_code text,
  add column if not exists annual_budget_item_id bigint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.project_names'::regclass
      and conname = 'project_names_central_office_format_code_fkey'
  ) then
    alter table public.project_names
      add constraint project_names_central_office_format_code_fkey
      foreign key (central_office_format_code)
      references public.project_delivery_formats(code)
      on delete restrict;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.project_names'::regclass
      and conname = 'project_names_main_department_format_code_fkey'
  ) then
    alter table public.project_names
      add constraint project_names_main_department_format_code_fkey
      foreign key (main_department_format_code)
      references public.project_delivery_formats(code)
      on delete restrict;
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.project_names'::regclass
      and conname = 'project_names_annual_budget_item_id_fkey'
  ) then
    alter table public.project_names
      add constraint project_names_annual_budget_item_id_fkey
      foreign key (annual_budget_item_id)
      references public.annual_budget_items(id)
      on delete restrict;
  end if;
end
$$;

comment on column public.project_names.central_office_format_code is
  'Optional delivery format for the central office (ЦА).';
comment on column public.project_names.main_department_format_code is
  'Optional delivery format for the main department (ГУ).';
comment on column public.project_names.annual_budget_item_id is
  'Optional annual budget dictionary item associated with the project.';

grant select on table public.project_delivery_formats to anon, authenticated;
grant select, insert, update, delete on table public.annual_budget_items to anon, authenticated;
grant usage, select on sequence public.annual_budget_items_id_seq to anon, authenticated;

notify pgrst, 'reload schema';
