create table if not exists public.material_types (
  code text primary key,
  name text not null unique,
  sort_order integer not null default 0,
  is_active boolean not null default true
);

create table if not exists public.material_statuses (
  code text primary key,
  name text not null unique,
  is_complete boolean not null default false,
  sort_order integer not null default 0,
  is_active boolean not null default true
);

insert into public.material_types (code, name, sort_order)
values
  ('presentation', 'Презентация', 10),
  ('scenario', 'Сценарий', 20),
  ('methodological_materials', 'Методические материалы', 30)
on conflict (code) do update
set
  name = excluded.name,
  sort_order = excluded.sort_order;

insert into public.material_statuses (code, name, is_complete, sort_order)
values
  ('not_started', 'Не начат', false, 10),
  ('in_progress', 'В работе', false, 20),
  ('ready', 'Готов', true, 30),
  ('needs_update', 'Требует актуализации', false, 40)
on conflict (code) do update
set
  name = excluded.name,
  is_complete = excluded.is_complete,
  sort_order = excluded.sort_order;

create table if not exists public.project_materials (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.project_names(id) on delete cascade,
  type_code text not null references public.material_types(code) on delete restrict,
  status_code text not null default 'not_started'
    references public.material_statuses(code) on delete restrict,
  title text,
  location text,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists project_materials_project_id_idx
  on public.project_materials (project_id);

comment on column public.project_materials.location is
  'A URL or a textual description of the material location in the internal organization system.';

notify pgrst, 'reload schema';
