create table if not exists public.cities (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true
);

create table if not exists public.divisions (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true
);

create table if not exists public.project_statuses (
  code text primary key,
  name text not null unique,
  is_terminal boolean not null default false,
  sort_order integer not null default 0,
  is_active boolean not null default true
);

create table if not exists public.project_kinds (
  code text primary key,
  name text not null unique,
  sort_order integer not null default 0,
  is_active boolean not null default true
);

create table if not exists public.directions (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  is_active boolean not null default true
);

create table if not exists public.certification_statuses (
  code text primary key,
  name text not null unique,
  grants_access boolean not null default false,
  sort_order integer not null default 0,
  is_active boolean not null default true
);

create table if not exists public.material_types (
  code text primary key,
  name text not null unique,
  sort_order integer not null default 0,
  is_active boolean not null default true
);

create table if not exists public.material_statuses (
  code text primary key,
  name text not null unique,
  is_complete boolean not null default false,
  sort_order integer not null default 0,
  is_active boolean not null default true
);

insert into public.project_statuses (code, name, is_terminal, sort_order)
values
  ('in_development', 'В разработке', false, 10),
  ('completed', 'Завершён', true, 20)
on conflict (code) do update
set
  name = excluded.name,
  is_terminal = excluded.is_terminal,
  sort_order = excluded.sort_order;

insert into public.project_kinds (code, name, sort_order)
values
  ('project', 'Проект', 10),
  ('program', 'Программа', 20),
  ('module', 'Модуль', 30)
on conflict (code) do update
set
  name = excluded.name,
  sort_order = excluded.sort_order;

insert into public.certification_statuses (code, name, grants_access, sort_order)
values
  ('in_training', 'В процессе сертификации', false, 10),
  ('certified', 'Сертифицирован', true, 20),
  ('suspended', 'Допуск приостановлен', false, 30),
  ('expired', 'Срок действия истёк', false, 40)
on conflict (code) do update
set
  name = excluded.name,
  grants_access = excluded.grants_access,
  sort_order = excluded.sort_order;

insert into public.material_types (code, name, sort_order)
values
  ('presentation', 'Презентация', 10),
  ('scenario', 'Сценарий', 20),
  ('methodological_materials', 'Методические материалы', 30)
on conflict (code) do update
set
  name = excluded.name,
  sort_order = excluded.sort_order;

insert into public.material_statuses (code, name, is_complete, sort_order)
values
  ('not_started', 'Не начат', false, 10),
  ('in_progress', 'В работе', false, 20),
  ('ready', 'Готов', true, 30),
  ('needs_update', 'Требует актуализации', false, 40)
on conflict (code) do update
set
  name = excluded.name,
  is_complete = excluded.is_complete,
  sort_order = excluded.sort_order;

alter table public.trainers
  add column if not exists city_id bigint references public.cities(id) on delete set null,
  add column if not exists division_id bigint references public.divisions(id) on delete set null;

alter table public.project_names
  add column if not exists status_code text not null default 'in_development'
    references public.project_statuses(code) on delete restrict,
  add column if not exists kind_code text not null default 'project'
    references public.project_kinds(code) on delete restrict,
  add column if not exists parent_project_id bigint
    references public.project_names(id) on delete restrict,
  add column if not exists module_position integer,
  add column if not exists customer text,
  add column if not exists lead_methodologist_id bigint
    references public.trainers(id) on delete set null,
  add column if not exists target_audience text,
  add column if not exists goals text,
  add column if not exists short_description text,
  add constraint project_names_not_own_parent
    check (parent_project_id is null or parent_project_id <> id),
  add constraint project_names_module_position_positive
    check (module_position is null or module_position > 0);

create table if not exists public.project_direction_links (
  project_id bigint not null references public.project_names(id) on delete cascade,
  direction_id bigint not null references public.directions(id) on delete restrict,
  primary key (project_id, direction_id)
);

create table if not exists public.trainer_certifications (
  id bigint generated by default as identity primary key,
  trainer_id bigint not null references public.trainers(id) on delete cascade,
  project_id bigint not null references public.project_names(id) on delete cascade,
  status_code text not null default 'certified'
    references public.certification_statuses(code) on delete restrict,
  valid_from date,
  valid_until date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (trainer_id, project_id),
  constraint trainer_certifications_validity_check
    check (valid_until is null or valid_from is null or valid_until >= valid_from)
);

create table if not exists public.project_materials (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.project_names(id) on delete cascade,
  type_code text not null references public.material_types(code) on delete restrict,
  status_code text not null default 'not_started'
    references public.material_statuses(code) on delete restrict,
  title text,
  location text,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists trainers_city_id_idx
  on public.trainers (city_id);
create index if not exists trainers_division_id_idx
  on public.trainers (division_id);
create index if not exists project_names_parent_project_id_idx
  on public.project_names (parent_project_id);
create index if not exists project_names_status_code_idx
  on public.project_names (status_code);
create index if not exists project_names_lead_methodologist_id_idx
  on public.project_names (lead_methodologist_id);
create index if not exists trainer_certifications_trainer_id_idx
  on public.trainer_certifications (trainer_id);
create index if not exists trainer_certifications_project_id_idx
  on public.trainer_certifications (project_id);
create index if not exists project_materials_project_id_idx
  on public.project_materials (project_id);

create or replace function public.prevent_project_hierarchy_cycle()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.parent_project_id is null then
    return new;
  end if;

  if new.parent_project_id = new.id then
    raise exception 'A project cannot be its own parent';
  end if;

  if exists (
    with recursive ancestors as (
      select p.id, p.parent_project_id
      from public.project_names p
      where p.id = new.parent_project_id

      union all

      select p.id, p.parent_project_id
      from public.project_names p
      join ancestors a on p.id = a.parent_project_id
    )
    select 1
    from ancestors
    where id = new.id
  ) then
    raise exception 'A project hierarchy cycle is not allowed';
  end if;

  return new;
end;
$$;

drop trigger if exists prevent_project_hierarchy_cycle
  on public.project_names;
create trigger prevent_project_hierarchy_cycle
before insert or update of parent_project_id
on public.project_names
for each row
execute function public.prevent_project_hierarchy_cycle();

create or replace view public.trainer_effective_project_access as
with recursive project_descendants as (
  select
    p.id as granted_project_id,
    p.id as accessible_project_id
  from public.project_names p

  union all

  select
    d.granted_project_id,
    child.id as accessible_project_id
  from project_descendants d
  join public.project_names child
    on child.parent_project_id = d.accessible_project_id
)
select distinct
  certification.trainer_id,
  descendants.accessible_project_id as project_id,
  certification.project_id as granted_by_project_id,
  certification.id as certification_id
from public.trainer_certifications certification
join public.certification_statuses status
  on status.code = certification.status_code
 and status.grants_access
join project_descendants descendants
  on descendants.granted_project_id = certification.project_id
where
  (certification.valid_from is null or certification.valid_from <= current_date)
  and (certification.valid_until is null or certification.valid_until >= current_date);

comment on column public.project_names.parent_project_id is
  'A module belongs to at most one parent program. Null means a top-level project or program.';
comment on column public.project_names.lead_methodologist_id is
  'The primary methodologist, selected from trainers.';
comment on table public.trainer_certifications is
  'Direct trainer certification records. Program access is inherited by all descendant modules through trainer_effective_project_access.';
comment on column public.project_materials.location is
  'A URL or a textual description of the material location in the internal organization system.';
